include: package:very_good_analysis/analysis_options.yaml

analyzer:
  # Pastas e arquivos que o analisador deve ignorar completamente
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "lib/generated_plugin_registrant.dart"
    - "build/**"

  # Adicione o bloco errors aqui para silenciar avisos do analisador
  errors:
    inference_failure_on_instance_creation: ignore
    inference_failure_on_untyped_parameter: ignore

linter:
  rules:
    # ========================================================================
    # REGRAS DESATIVADAS (Eram essas que geravam os +1000 erros)
    # ========================================================================
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    sort_constructors_first: false
    always_put_required_named_parameters_first: false
    avoid_classes_with_only_static_members: false
    sort_pub_dependencies: false
    prefer_int_literals: false

    # ========================================================================
    # REGRAS ATIVADAS (Úteis para qualidade e padronização)
    # ========================================================================
    prefer_single_quotes: true
    avoid_print: true
    unnecessary_statements: true

    # NOVAS REGRAS PARA SILENCIAR O RUÍDO:
    avoid_catches_without_on_clauses: false
    cascade_invocations: false
    discarded_futures: false
    unawaited_futures: false
    avoid_positional_boolean_parameters: false

    # IMPORTANTE: As regras de "inference_failure" foram removidas daqui!
