// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2O8lsaSHX0B8U6zFc1pIiVE3GykwnNVo',
    appId: '1:78049230117:web:8010bbd6955ad702ee6ecc',
    messagingSenderId: '78049230117',
    projectId: 'roblox-casa',
    authDomain: 'roblox-casa.firebaseapp.com',
    storageBucket: 'roblox-casa.firebasestorage.app',
    measurementId: 'G-E1XXCSSWNH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRl0sEPa0pSGeFubpv2Er-m0ylZVE7PKg',
    appId: '1:78049230117:android:58fbd39e89ed30c5ee6ecc',
    messagingSenderId: '78049230117',
    projectId: 'roblox-casa',
    storageBucket: 'roblox-casa.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8ODQVYeZmMvaycI3orBIRNwZ1BjZX9G4',
    appId: '1:78049230117:ios:dccb10643b0fb6f8ee6ecc',
    messagingSenderId: '78049230117',
    projectId: 'roblox-casa',
    storageBucket: 'roblox-casa.firebasestorage.app',
    iosBundleId: 'com.example.pagaOQueMeDeve',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8ODQVYeZmMvaycI3orBIRNwZ1BjZX9G4',
    appId: '1:78049230117:ios:dccb10643b0fb6f8ee6ecc',
    messagingSenderId: '78049230117',
    projectId: 'roblox-casa',
    storageBucket: 'roblox-casa.firebasestorage.app',
    iosBundleId: 'com.example.pagaOQueMeDeve',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2O8lsaSHX0B8U6zFc1pIiVE3GykwnNVo',
    appId: '1:78049230117:web:bde9b88e0b7f2a90ee6ecc',
    messagingSenderId: '78049230117',
    projectId: 'roblox-casa',
    authDomain: 'roblox-casa.firebaseapp.com',
    storageBucket: 'roblox-casa.firebasestorage.app',
    measurementId: 'G-9GG8LVVFL2',
  );
}
